# Generated by Django 5.0.3 on 2024-03-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_alter_articles_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.CharField(choices=[('standard', 'Standard'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=10)),
                ('block_position', models.CharField(max_length=50)),
                ('row', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('show_title', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('is_external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('my_order', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
