# Generated by Django 5.0.3 on 2024-03-23 06:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_articles_id_alter_tags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
